clean_urls: false

timezone: Europe/London

debug: false

authenticate:
  password: 
  error: Your password was incorrect.
  ip_whitelist: # eg. 127.0.0.1
  
cookie:
  prefix: prototype-
  lifetime: 604800 # 1 week

triggers:
  data: _data
  shorturl: _p
  export: _export
  auth: _auth
  assets: _assets
  user: _user

user:
  identify: username
  auth: password
  login:
    redirect: /
    error: Your login details were incorrect.
  logout:
    redirect: /

name_overrides:
  '/' : 'Home'

data:
  csv:
    headers: true
    delimiter: ','
    enclosure: '"'
    escape: '\'
    id_header: id
  
routes:
  # "posts/(:all)" : "posts/post"

extensions:
  # example: ExampleExtension.php
  
snippets:
  images:
    placeholder:
      service: dummyimage
      width: 200
      height: 200
      category: people